language: python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
install:
  - "pip install -r tests/requirements.txt"
  - "pip install coveralls"
script:
  - "nosetests"
  - "coverage xml"
notifications:
  email:
    on_success: "change"
    on_failure: "always"
after_success:
  - "coveralls"
