language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install:
  - "pip install -r tests/requirements.txt"
  - "pip install coveralls"
script:
  - "nosetests --with-coverage"
  - "coverage xml"
notifications:
  email:
    on_success: "change"
    on_failure: "always"
after_success:
  - "coveralls"
